spring:
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:yennichi
    username: sa
    password: 

  h2:
    console:
      enabled: true
      
debug: true

image:
  local: true